version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: vita_postgres
    restart: always
    environment:
      POSTGRES_DB: health_clinical_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_password_segura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: vita_redis
    ports:
      - "6379:6379"

  web:
    build: ./backend
    container_name: vita_django
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-local-key
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgres://postgres:admin_password_segura@db:5432/health_clinical_db
      - DB_NAME=health_clinical_db
      - DB_USER=postgres
      - DB_PASSWORD=admin_password_segura
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    container_name: vita_celery
    command: celery -A config worker --loglevel=info --pool=solo
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-local-key
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgres://postgres:admin_password_segura@db:5432/health_clinical_db
      - DB_NAME=health_clinical_db
      - DB_USER=postgres
      - DB_PASSWORD=admin_password_segura
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
