# Generated by Django 5.2.15 on 2026-06-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_metricasmodeloml'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardkpis',
            name='alertas_glucosa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardkpis',
            name='alertas_saturacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardkpis',
            name='alertas_sistolica',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardkpis',
            name='pacientes_alcohol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardkpis',
            name='pacientes_antecedentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardkpis',
            name='pacientes_obesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardkpis',
            name='pacientes_saturacion_baja',
            field=models.IntegerField(default=0),
        ),
    ]
