# Generated by Django 4.2 on 2026-06-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_dashboardkpis_alertas_glucosa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fase', models.CharField(default='', max_length=32)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('detalle', models.TextField(blank=True, default='')),
                ('logs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
